ARG JAVA_VERSION

FROM jruby:9.4-jdk${JAVA_VERSION}

ENV JAVA_VERSION=$JAVA_VERSION

# Installing packages
RUN apt-get update && apt-get upgrade -y && apt-get install -y git python3-pip

# Installing boltkit
RUN pip3 install --user git+https://github.com/klobuczek/boltkit@1.3#egg=boltkit
RUN echo "export PATH=/root/.local/bin:$PATH" >> ~/.bashrc

WORKDIR /app
COPY . .
RUN ./bin/setup

CMD ["bundle exec rspec spec"]
