source "https://rubygems.org"

# Specify your gem's dependencies in testkit-backend.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "neo4j-#{RUBY_PLATFORM == 'java' ? 'java' : 'ruby'}-driver", path: '..'
